apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermariogame-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermariogame
  template:
    metadata:
      labels:
        app: supermariogame
    spec:
      containers:
      - name: supermariogame-container
        image: testoranit/supermariogitopsproject:1  # <-- Add tag here
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: supermariogame-service
spec:
  selector:
    app: supermariogame
  ports:
  - protocol: TCP
    port: 8600
    targetPort: 8080
  type: LoadBalancer
